"""Bug Bounty Report Generator."""

import json
from pathlib import Path
from typing import Dict, List, Any
from datetime import datetime

from ..utils.logger import logger


class BugBountyReporter:
    """Generate professional bug bounty reports."""

    def __init__(self, output_dir: str = "./output/bugbounty"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_report(self, findings: List[Dict], target: str) -> str:
        """Generate a markdown report from findings."""
        logger.info(f"[*] Generating report for {target}")

        severity_counts = {
            "Critical": 0, "High": 0, "Medium": 0, "Low": 0, "Info": 0
        }
        for finding in findings:
            severity = finding.get("severity", "Info")
            severity_counts[severity] = severity_counts.get(severity, 0) + 1

        report = f"""# Security Assessment Report

**Target:** {target}
**Date:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Assessor:** Prometheus AI Security Scanner

---

## Executive Summary

| Severity | Count |
|----------|-------|
| Critical | {severity_counts['Critical']} |
| High | {severity_counts['High']} |
| Medium | {severity_counts['Medium']} |
| Low | {severity_counts['Low']} |
| Info | {severity_counts['Info']} |
| **Total** | **{len(findings)}** |

---

## Findings

"""

        for i, finding in enumerate(findings, 1):
            report += f"""### Finding {i}: {finding.get('type', 'Unknown')}

**Severity:** {finding.get('severity', 'Unknown')}
**URL:** {finding.get('url', 'N/A')}
**Description:** {finding.get('description', 'No description')}

**Recommendation:** {finding.get('recommendation', 'No recommendation')}

---

"""

        report += f"""
## Disclaimer

This report was generated by Prometheus AI Security Scanner for authorized security testing purposes only. The findings should be verified manually before submission to bug bounty programs.

Generated by: Prometheus AI v1.0.0
"""

        # Save report
        report_file = self.output_dir / target / "report.md"
        report_file.parent.mkdir(parents=True, exist_ok=True)
        with open(report_file, "w") as f:
            f.write(report)

        logger.info(f"[green]Report saved to {report_file}[/green]")
        return str(report_file)

    def generate_hackerone_report(self, finding: Dict) -> str:
        """Generate a HackerOne-style report for a single finding."""
        return f"""## Summary

{finding.get('description', 'Security vulnerability discovered')}

## Vulnerability Details

**Type:** {finding.get('type', 'Unknown')}
**Severity:** {finding.get('severity', 'Unknown')}
**CWE:** {finding.get('cwe', 'CWE-693: Protection Mechanism Failure')}

## Steps to Reproduce

1. Navigate to {finding.get('url', '[TARGET_URL]')}
2. [Add detailed steps here]

## Impact

{finding.get('impact', 'Potential security risk to the application and its users.')}

## Remediation

{finding.get('recommendation', 'Apply security best practices and patches.')}

## Supporting Material

[Add screenshots, logs, or other evidence here]
"""
